### ISSUE TITLE
Support for configuration file.

### ISSUE THREAD

**Issue by phracek** [sclorg/auto-merger#10]
For case that we need to support not only 'sclorg' organization
let's add support for configuration files.

The yaml file could be:

```yaml
github_org:
   review_labels:
    - []
   merged_labels:
    - []
   receiver_emails:
   - []
   approvals: 2
   lifespan: // in days  
```
